version: '3.1'

services:
  db_postgres:
    image: postgres
    container_name: db_coffee_rustic
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=coffee
